[project]
name = "ai-in-a-box"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gpiozero>=2.0.1",
    "numpy>=2.4.1",
    "openai>=2.15.0",
    "openai-agents[realtime]>=0.7.0",
    "pynput>=1.8.1",
    "python-dotenv>=1.2.1",
    "sounddevice>=0.5.5",
]
